services:
  template.sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: temp.sql
    ports:
      - "9003:1433"
    environment: 
      "ACCEPT_EULA": "Y"
      "SA_PASSWORD": "sa!Password-123"