//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Template.MvcWebApp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string Home_Index_Title {
            get {
                return ResourceManager.GetString("Home_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Home_Index_Title_Welcome {
            get {
                return ResourceManager.GetString("Home_Index_Title_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Home_Privacy_Title {
            get {
                return ResourceManager.GetString("Home_Privacy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource..
        /// </summary>
        public static string Identity_Account_AccessDenied_Content {
            get {
                return ResourceManager.GetString("Identity_Account_AccessDenied_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string Identity_Account_AccessDenied_Title {
            get {
                return ResourceManager.GetString("Identity_Account_AccessDenied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string Identity_Account_ConfirmEmail_Title {
            get {
                return ResourceManager.GetString("Identity_Account_ConfirmEmail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email change.
        /// </summary>
        public static string Identity_Account_ConfirmEmailChange_Title {
            get {
                return ResourceManager.GetString("Identity_Account_ConfirmEmailChange_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with &lt;strong&gt;@Model.ProviderDisplayName&lt;/strong&gt;.
        ///    Please enter an email address for this site below and click the Register button to finish
        ///    logging in..
        /// </summary>
        public static string Identity_Account_ExternalLogin_Description {
            get {
                return ResourceManager.GetString("Identity_Account_ExternalLogin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Identity_Account_ExternalLogin_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_ExternalLogin_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your {0} account..
        /// </summary>
        public static string Identity_Account_ExternalLogin_Subtitle {
            get {
                return ResourceManager.GetString("Identity_Account_ExternalLogin_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Identity_Account_ExternalLogin_Title {
            get {
                return ResourceManager.GetString("Identity_Account_ExternalLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Identity_Account_ForgotPassword_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_ForgotPassword_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string Identity_Account_ForgotPassword_Subtitle {
            get {
                return ResourceManager.GetString("Identity_Account_ForgotPassword_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Identity_Account_ForgotPassword_Title {
            get {
                return ResourceManager.GetString("Identity_Account_ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string Identity_Account_ForgotPasswordConfirmation_Message {
            get {
                return ResourceManager.GetString("Identity_Account_ForgotPasswordConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password confirmation.
        /// </summary>
        public static string Identity_Account_ForgotPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("Identity_Account_ForgotPasswordConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string Identity_Account_Lockout_Message {
            get {
                return ResourceManager.GetString("Identity_Account_Lockout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string Identity_Account_Lockout_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Lockout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Identity_Account_Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Identity_Account_Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string Identity_Account_Login_LoginServices {
            get {
                return ResourceManager.GetString("Identity_Account_Login_LoginServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string Identity_Account_Login_RegisterNewUser {
            get {
                return ResourceManager.GetString("Identity_Account_Login_RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email confirmation.
        /// </summary>
        public static string Identity_Account_Login_ReserndConfirmation {
            get {
                return ResourceManager.GetString("Identity_Account_Login_ReserndConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Identity_Account_Login_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Login_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string Identity_Account_Login_Subtitle {
            get {
                return ResourceManager.GetString("Identity_Account_Login_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Identity_Account_Login_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login is protected with an authenticator app. Enter your authenticator code below..
        /// </summary>
        public static string Identity_Account_Login2FA_Description {
            get {
                return ResourceManager.GetString("Identity_Account_Login2FA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have access to your authenticator device? You can
        ///    &lt;a id=&quot;recovery-code-login&quot; asp-page=&quot;./LoginWithRecoveryCode&quot; asp-route-returnUrl=&quot;@Model.ReturnUrl&quot;&gt;log in with a recovery code&lt;/a&gt;..
        /// </summary>
        public static string Identity_Account_Login2FA_RecoverCodeMessage {
            get {
                return ResourceManager.GetString("Identity_Account_Login2FA_RecoverCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Identity_Account_Login2FA_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Login2FA_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string Identity_Account_Login2FA_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Login2FA_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested to log in with a recovery code. This login will not be remembered until you provide
        ///    an authenticator app code at log in or disable 2FA and log in again..
        /// </summary>
        public static string Identity_Account_LoginRecoveryCode_Description {
            get {
                return ResourceManager.GetString("Identity_Account_LoginRecoveryCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Identity_Account_LoginRecoveryCode_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_LoginRecoveryCode_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code verification.
        /// </summary>
        public static string Identity_Account_LoginRecoveryCode_Title {
            get {
                return ResourceManager.GetString("Identity_Account_LoginRecoveryCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged out of the application..
        /// </summary>
        public static string Identity_Account_Logout_Confirmation {
            get {
                return ResourceManager.GetString("Identity_Account_Logout_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Logout.
        /// </summary>
        public static string Identity_Account_Logout_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Logout_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Identity_Account_Logout_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Logout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string Identity_Account_Manage_ChangePassword_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ChangePassword_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Identity_Account_Manage_ChangePassword_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Identity_Account_Manage_ChangePasswordModel_OldPassword {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ChangePasswordModel_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string Identity_Account_Manage_DeletePersonalData_Description {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_DeletePersonalData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data and close my account.
        /// </summary>
        public static string Identity_Account_Manage_DeletePersonalData_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_DeletePersonalData_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Personal Data.
        /// </summary>
        public static string Identity_Account_Manage_DeletePersonalData_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_DeletePersonalData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///        &lt;strong&gt;This action only disables 2FA.&lt;/strong&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        Disabling 2FA does not change the keys used in authenticator apps. If you wish to change the key
        ///        used in an authenticator app you should &lt;a asp-page=&quot;./ResetAuthenticator&quot;&gt;reset your authenticator keys.&lt;/a&gt;
        ///    &lt;/p&gt;.
        /// </summary>
        public static string Identity_Account_Manage_Disable2fa_Description {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_Disable2fa_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string Identity_Account_Manage_Disable2fa_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_Disable2fa_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable two-factor authentication(2FA).
        /// </summary>
        public static string Identity_Account_Manage_Disable2fa_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_Disable2fa_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Your Data.
        /// </summary>
        public static string Identity_Account_Manage_DownloadPersonalData_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_DownloadPersonalData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email.
        /// </summary>
        public static string Identity_Account_Manage_Email_Change {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_Email_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification email.
        /// </summary>
        public static string Identity_Account_Manage_Email_Send {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_Email_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Email.
        /// </summary>
        public static string Identity_Account_Manage_Email_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_Email_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a two-factor authenticator app like Microsoft Authenticator for
        ///                &lt;a href=&quot;https://go.microsoft.com/fwlink/?Linkid=825072&quot;&gt;Android&lt;/a&gt; and
        ///                &lt;a href=&quot;https://go.microsoft.com/fwlink/?Linkid=825073&quot;&gt;iOS&lt;/a&gt; or
        ///                Google Authenticator for
        ///                &lt;a href=&quot;https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&amp;amp;hl=en&quot;&gt;Android&lt;/a&gt; and
        ///                &lt;a href=&quot;https://itunes.apple.com/us/app/google-authenticator/id38849760 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Identity_Account_Manage_EnableAuthenticator_Step1 {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_EnableAuthenticator_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR Code or enter this key &lt;kbd&gt;{0}&lt;/kbd&gt; into your two factor authenticator app. Spaces and casing do not matter..
        /// </summary>
        public static string Identity_Account_Manage_EnableAuthenticator_Step2 {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_EnableAuthenticator_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have scanned the QR code or input the key above, your two factor authentication app will provide you with a unique code. Enter the code in the confirmation box below..
        /// </summary>
        public static string Identity_Account_Manage_EnableAuthenticator_Step3 {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_EnableAuthenticator_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use an authenticator app go through the following steps:.
        /// </summary>
        public static string Identity_Account_Manage_EnableAuthenticator_Steps {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_EnableAuthenticator_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Identity_Account_Manage_EnableAuthenticator_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_EnableAuthenticator_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure authenticator app.
        /// </summary>
        public static string Identity_Account_Manage_EnableAuthenticator_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_EnableAuthenticator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another service to log in..
        /// </summary>
        public static string Identity_Account_Manage_ExternalLogins_AddAnother {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ExternalLogins_AddAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Identity_Account_Manage_ExternalLogins_Remove {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ExternalLogins_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        public static string Identity_Account_Manage_ExternalLogins_Subitle {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ExternalLogins_Subitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string Identity_Account_Manage_ExternalLogins_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ExternalLogins_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///        &lt;span class=&quot;glyphicon glyphicon-warning-sign&quot;&gt;&lt;/span&gt;
        ///        &lt;strong&gt;Put these codes in a safe place.&lt;/strong&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        If you lose your device and don&apos;t have the recovery codes you will lose access to your account.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        Generating new recovery codes does not change the keys used in authenticator apps. If you wish to change the key
        ///        used in an authenticator app you should &lt;a asp-page=&quot;./ResetAuthenticator&quot;&gt;reset your authenticator keys.&lt;/a&gt;
        ///    &lt;/p&gt;.
        /// </summary>
        public static string Identity_Account_Manage_GenerateRecoveryCodes_Description {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_GenerateRecoveryCodes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Recovery Codes.
        /// </summary>
        public static string Identity_Account_Manage_GenerateRecoveryCodes_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_GenerateRecoveryCodes_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate two-factor authentication(2FA) recovery codes.
        /// </summary>
        public static string Identity_Account_Manage_GenerateRecoveryCodes_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_GenerateRecoveryCodes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Identity_Account_Manage_Index_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_Index_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Identity_Account_Manage_Index_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string Identity_Account_Manage_Layout_Subtitle {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_Layout_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string Identity_Account_Manage_Layout_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string Identity_Account_Manage_ManageNav_2FA {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ManageNav_2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Identity_Account_Manage_ManageNav_Email {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ManageNav_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External logins.
        /// </summary>
        public static string Identity_Account_Manage_ManageNav_ExternalLogins {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ManageNav_ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Identity_Account_Manage_ManageNav_Password {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ManageNav_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string Identity_Account_Manage_ManageNav_PersonalData {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ManageNav_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Identity_Account_Manage_ManageNav_Profile {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ManageNav_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Identity_Account_Manage_PersonalData_Delete {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_PersonalData_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Your account contains personal data that you have given us. This page allows you to download or delete that data.&lt;/p&gt;
        ///        &lt;p&gt;
        ///            &lt;strong&gt;Deleting this data will permanently remove your account, and this cannot be recovered.&lt;/strong&gt;
        ///        &lt;/p&gt;.
        /// </summary>
        public static string Identity_Account_Manage_PersonalData_Description {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_PersonalData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Identity_Account_Manage_PersonalData_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_PersonalData_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        public static string Identity_Account_Manage_PersonalData_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_PersonalData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///        &lt;span class=&quot;glyphicon glyphicon-warning-sign&quot;&gt;&lt;/span&gt;
        ///        &lt;strong&gt;If you reset your authenticator key your authenticator app will not work until you reconfigure it.&lt;/strong&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        This process disables 2FA until you verify your authenticator app.
        ///        If you do not complete your authenticator app configuration you may lose access to your account.
        ///    &lt;/p&gt;.
        /// </summary>
        public static string Identity_Account_Manage_ResetAuthenticator_Description {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ResetAuthenticator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator key.
        /// </summary>
        public static string Identity_Account_Manage_ResetAuthenticator_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ResetAuthenticator_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator key.
        /// </summary>
        public static string Identity_Account_Manage_ResetAuthenticator_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ResetAuthenticator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local account so you can log in without an external login..
        /// </summary>
        public static string Identity_Account_Manage_SetPassword_Description {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_SetPassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string Identity_Account_Manage_SetPassword_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_SetPassword_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your password.
        /// </summary>
        public static string Identity_Account_Manage_SetPassword_Subtitle {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_SetPassword_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string Identity_Account_Manage_SetPassword_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_SetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///        &lt;strong&gt;Put these codes in a safe place.&lt;/strong&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        If you lose your device and don&apos;t have the recovery codes you will lose access to your account.
        ///    &lt;/p&gt;.
        /// </summary>
        public static string Identity_Account_Manage_ShowRecoveryCodes_Description {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ShowRecoveryCodes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery codes.
        /// </summary>
        public static string Identity_Account_Manage_ShowRecoveryCodes_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_ShowRecoveryCodes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add authenticator app.
        /// </summary>
        public static string Identity_Account_Manage_TwoFactorAuthentication_AddApp {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_TwoFactorAuthentication_AddApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;You have no recovery codes left.&lt;/strong&gt;
        ///&lt;p&gt;You must &lt;a asp-page=&quot;./GenerateRecoveryCodes&quot;&gt;generate a new set of recovery codes&lt;/a&gt; before you can log in with a recovery code.&lt;/p&gt;.
        /// </summary>
        public static string Identity_Account_Manage_TwoFactorAuthentication_Alert0 {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_TwoFactorAuthentication_Alert0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;You have 1 recovery code left.&lt;/strong&gt;
        ///&lt;p&gt;You can &lt;a asp-page=&quot;./GenerateRecoveryCodes&quot;&gt;generate a new set of recovery codes&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string Identity_Account_Manage_TwoFactorAuthentication_Alert1 {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_TwoFactorAuthentication_Alert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;You have {0} recovery codes left.&lt;/strong&gt;
        ///&lt;p&gt;You should &lt;a asp-page=&quot;./GenerateRecoveryCodes&quot;&gt;generate a new set of recovery codes&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string Identity_Account_Manage_TwoFactorAuthentication_Alert2 {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_TwoFactorAuthentication_Alert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator app.
        /// </summary>
        public static string Identity_Account_Manage_TwoFactorAuthentication_AuthenticatorTitle {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_TwoFactorAuthentication_AuthenticatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string Identity_Account_Manage_TwoFactorAuthentication_Disable {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_TwoFactorAuthentication_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget this browser.
        /// </summary>
        public static string Identity_Account_Manage_TwoFactorAuthentication_Forgot {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_TwoFactorAuthentication_Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Privacy and cookie policy have not been accepted.&lt;/strong&gt;
        ///&lt;p&gt;You must accept the policy before you can enable two factor authentication.&lt;/p&gt;.
        /// </summary>
        public static string Identity_Account_Manage_TwoFactorAuthentication_PolicyNotAccepted {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_TwoFactorAuthentication_PolicyNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator app.
        /// </summary>
        public static string Identity_Account_Manage_TwoFactorAuthentication_ResetApp {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_TwoFactorAuthentication_ResetApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset recovery codes.
        /// </summary>
        public static string Identity_Account_Manage_TwoFactorAuthentication_ResetRecoveryCodes {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_TwoFactorAuthentication_ResetRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up authenticator app.
        /// </summary>
        public static string Identity_Account_Manage_TwoFactorAuthentication_SetApp {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_TwoFactorAuthentication_SetApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication(2FA).
        /// </summary>
        public static string Identity_Account_Manage_TwoFactorAuthentication_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Manage_TwoFactorAuthentication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to register..
        /// </summary>
        public static string Identity_Account_Register_LoginServices {
            get {
                return ResourceManager.GetString("Identity_Account_Register_LoginServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Identity_Account_Register_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_Register_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string Identity_Account_Register_Subtitle {
            get {
                return ResourceManager.GetString("Identity_Account_Register_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Identity_Account_Register_Title {
            get {
                return ResourceManager.GetString("Identity_Account_Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app does not currently have a real email sender registered, see &lt;a href=&quot;https://aka.ms/aspaccountconf&quot;&gt;these docs&lt;/a&gt; for how to configure a real email sender.
        ///    Normally this would be emailed: &lt;a id=&quot;confirm-link&quot; href=&quot;@Model.EmailConfirmationUrl&quot;&gt;Click here to confirm your account&lt;/a&gt;.
        /// </summary>
        public static string Identity_Account_RegisterConfirmation_Description {
            get {
                return ResourceManager.GetString("Identity_Account_RegisterConfirmation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to confirm your account..
        /// </summary>
        public static string Identity_Account_RegisterConfirmation_Message {
            get {
                return ResourceManager.GetString("Identity_Account_RegisterConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register confirmation.
        /// </summary>
        public static string Identity_Account_RegisterConfirmation_Title {
            get {
                return ResourceManager.GetString("Identity_Account_RegisterConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string Identity_Account_ResendEmailConfirmation_Subitle {
            get {
                return ResourceManager.GetString("Identity_Account_ResendEmailConfirmation_Subitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string Identity_Account_ResendEmailConfirmation_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_ResendEmailConfirmation_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email confirmation.
        /// </summary>
        public static string Identity_Account_ResendEmailConfirmation_Title {
            get {
                return ResourceManager.GetString("Identity_Account_ResendEmailConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please &lt;a asp-page=&quot;./Login&quot;&gt;click here to log in&lt;/a&gt;..
        /// </summary>
        public static string Identity_Account_ResetPasswordConfirmation_Content {
            get {
                return ResourceManager.GetString("Identity_Account_ResetPasswordConfirmation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string Identity_Account_ResetPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("Identity_Account_ResetPasswordConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Identity_Account_RestPassword_Submit {
            get {
                return ResourceManager.GetString("Identity_Account_RestPassword_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string Identity_Account_RestPassword_Subtitle {
            get {
                return ResourceManager.GetString("Identity_Account_RestPassword_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Identity_Account_RestPassword_Title {
            get {
                return ResourceManager.GetString("Identity_Account_RestPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Layout_Footer_Privacy {
            get {
                return ResourceManager.GetString("Layout_Footer_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Layout_Navbar_Home {
            get {
                return ResourceManager.GetString("Layout_Navbar_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}!.
        /// </summary>
        public static string Layout_Navbar_LoggedUser {
            get {
                return ResourceManager.GetString("Layout_Navbar_LoggedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string Layout_Navbar_LoggedUser_Title {
            get {
                return ResourceManager.GetString("Layout_Navbar_LoggedUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Layout_Navbar_Login {
            get {
                return ResourceManager.GetString("Layout_Navbar_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Layout_Navbar_Logout {
            get {
                return ResourceManager.GetString("Layout_Navbar_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Layout_Navbar_Privacy {
            get {
                return ResourceManager.GetString("Layout_Navbar_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Layout_Navbar_Register {
            get {
                return ResourceManager.GetString("Layout_Navbar_Register", resourceCulture);
            }
        }
    }
}
