name: Feature tests


on:
  push:
    branches:
      - 'feature/*'

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Unit Tests
      run: docker compose -f ./src/Template/docker-compose.unittests.yml up
      continue-on-error: false