# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Template-Web-Demo

on:
  push:
    branches:
      - master
  workflow_dispatch:
  #Permite el deploy manual
  
env:
    WEBAPPPATH: '${{ github.workspace }}/src/Template/Template.MvcWebApp'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          
      - name: Install dependencies
        run: dotnet restore ${{env.WEBAPPPATH}}

      - name: Build and publish
        run: |
            dotnet build --configuration Release --no-restore ${{env.WEBAPPPATH}}
            dotnet publish -c Release --no-build -o ${{env.DOTNET_ROOT}}/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Template-Web-Demo'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FB17B91993324E6EA0AA926CEC5A3E4C }}
          package: .
